Add overview and resource info to README
flutter/flutter_markdown pull request #268
Opened 2020-09-01 21:49 UTC by mjordan56

Added overview and Markdown syntax specification information with links to help users of the package understand Markdown syntax and how the package implements Markdown. Also added references to online Markdown viewer and additional resources.

2020-09-03 00:13 UTC, domesticmouse requested changes

2020-09-03 00:13 UTC, domesticmouse commented on README.md
> +markdown package then uses the
ditto

2020-09-03 00:13 UTC, domesticmouse commented on README.md
> +The flutter_markdown package uses the markdown package to parse the Markdown
s/flutter_markdown package/`flutter_markdown` package/

2020-09-03 00:13 UTC, domesticmouse commented on README.md
> +The CommonMark specification brings order to and clarifies the Markdown syntax
add paragraph break here?

2020-09-03 00:13 UTC, domesticmouse commented on README.md
> +The markdown package, and in extension, the flutter_markdown package, supports
`markdown` and `flutter_markdown`

2020-09-03 03:30 UTC, mjordan56 commented on README.md
> +The markdown package parses Markdown syntax into HTML. The markdown package
Good suggestion. I'll perform a global search and update the relevant markdown and flutter_markdown package references.

2020-09-03 03:30 UTC, domesticmouse commented on README.md
> +## Flutter Isn't HTML
Suggestion: "Flutter isn't a web browser" 
Alternative: "Flutter isn't a HTML renderer"

thoughts?

2020-09-03 03:30 UTC, mjordan56 commented on README.md
> +markdown package then uses the
ditto as well for the fix.

2020-09-03 03:31 UTC, mjordan56 commented on README.md
> +The CommonMark specification brings order to and clarifies the Markdown syntax
sure, paragraph break added.

2020-09-03 03:31 UTC, mjordan56 commented on README.md
> +The markdown package, and in extension, the flutter_markdown package, supports
ditto on the change

2020-09-03 03:31 UTC, domesticmouse reviewed
I'm going to rope in @mit-mit to get a second pair of eyes on this change

2020-09-03 03:34 UTC, mjordan56 commented on README.md
> +## Flutter Isn't HTML
I like your alternative suggestion best. What I want to convey is that Flutter isn't interpreting and rendering HTML as a browser would do with HTML that is passed through. I'll make the change to your alternative suggestion.

2020-09-03 03:41 UTC, mjordan56 commented
@domesticmouse I think I may have screwed up that last re-review request. I thought the HTML renderer title change was still pending for review. I agree with having more eyes on the README.md changes. It never hurts to have another set of eyes review the changes. Thanks.

2020-09-03 07:00 UTC, domesticmouse commented on README.md
> +## Flutter Isn't HTML
sounds good =)

2020-09-03 07:02 UTC, domesticmouse approved these changes
I'll wait for @mit-mit's approval before merging.

2020-09-03 10:46 UTC, mit-mit commented on README.md
> +The `markdown` package parses Markdown syntax into HTML. The `markdown` package
This paragraphs seems a bit too detailed; more consumers of this package are not likely to need details such as markdown using the visitor pattern. I'd do something simpler like:

`flutter_markdown` is built on top of the Dart [`markdown`](https://pub.dev/packages/markdown) package, which is uses to parse the markdown into an abstract syntax tree (AST), which represent an HTML representation of the Markdown data.

2020-09-03 10:46 UTC, mit-mit commented on README.md
> +The [`flutter_markdown`](https://pub.dev/packages/flutter_markdown) package
Remove the Dart part from here, as that is covered in the next paragraph, i.e. simplify to:

The [`flutter_markdown`](https://pub.dev/packages/flutter_markdown) package
can be used to render Markdown (a lightweight markup language) into a Flutter widget
containing a rich text representation.

2020-09-03 14:57 UTC, mjordan56 commented on README.md
> +The `markdown` package parses Markdown syntax into HTML. The `markdown` package
@mit-mit Thank you for your review comments. I've basically made the revisions you suggest in that I took the essence of your revision but I ran it through Grammarly.

2020-09-03 14:58 UTC, mjordan56 commented on README.md
> +The [`flutter_markdown`](https://pub.dev/packages/flutter_markdown) package
ditto. Suggested revisions made and ran through Grammarly.

2020-09-03 15:11 UTC, mit-mit approved these changes

2020-09-03 15:11 UTC, mit-mit commented
Thanks for the contribution @mjordan56 !

2020-09-04 22:50 UTC, domesticmouse commented
Thanks @mjordan56 for the word-smithing and @mit-mit for the review =)

2020-09-04 22:50 UTC, merged