Update README.md to fix emoji support section
flutter/flutter_markdown pull request #287
Opened 2020-10-01 18:00 UTC by ammaratef45

The emoji support example wasn't working and looks like currently `gitHubFlavored` is under `md.ExtensionSet, instead of `md` directly

2020-10-04 03:45 UTC, mjordan56 commented on README.md
> +    ),
Good catch. You are correct, gitHubFlavored is a static ExtensionSet definition and should be referenced as md.ExtensionSet.gitHubFlavored.

2020-10-04 03:48 UTC, mjordan56 requested changes
The first change is valid but I fail to see the difference in the second change. Am I missing a subtle change?

2020-10-04 03:48 UTC, mjordan56 commented on README.md
> +  - [Download PDF cheatsheet version](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf)
What is the change here? These two lines look identical to me. What am I missing?

2020-10-04 04:05 UTC, ammaratef45 commented on README.md
> +  - [Download PDF cheatsheet version](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf)
Looks like it's a formatting change that happened because of the IDE, any idea how to revert it? I guess it's the exact same thing

2020-10-04 22:37 UTC, mjordan56 commented on README.md
> +  - [Download PDF cheatsheet version](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf)
I suppose it's not a big problem but it is nice to have the changes in a PR explicitly for the changes without any extraneous diffs. If it's easy for you to do, see if you can diff the changes in the README.md file and revert the superfluous change. Git diff and other diff tools show the changes between the original file and the updated file. You can copy the original and paste it over the superfluous change.

2020-10-05 13:56 UTC, ammaratef45 commented on README.md
> +  - [Download PDF cheatsheet version](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf)
@mjordan56 Thanks, I've used `git revert` then made another commit with the change using my `VSCode` instead of the GitHub file editor and it worked 🥳

2020-10-05 14:33 UTC, mjordan56 commented on README.md
> +  - [Download PDF cheatsheet version](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf)
@ammaratef45 Cool! The changes look good to me. Thanks for cleaning up the PR.

2020-10-07 23:24 UTC, domesticmouse commented
Thakns @ammaratef45 and @mjordan56!

2020-10-07 23:24 UTC, merged