Allow custom list padding
flutter/flutter_markdown pull request #301
Opened 2020-11-16 19:43 UTC by cebr76

Replaced hard-coded list padding by checking for element's padding attribute. However, if no padding attribute is specified, the padding will still default to 4.0 #238

2020-11-16 19:45 UTC, cebr76 commented
> Thanks for your pull request. It looks like this may be your first contribution to a Google open source project (if not, look below for help). Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please visit https://cla.developers.google.com/ to sign.**
> 
> Once you've signed (or fixed any issues), please reply here with `@googlebot I signed it!` and we'll verify it.
> 
> #### What to do if you already signed the CLA
> ##### Individual signers
> * It's possible we don't have your GitHub username or you're using a different email address on your commit. Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> 
> ##### Corporate signers
> * Your company has a Point of Contact who decides which employees are authorized to participate. Ask your POC to be added to the group of authorized contributors. If you don't know who your Point of Contact is, direct the Google project maintainer to [go/cla#troubleshoot](http://go/cla#troubleshoot) ([Public version](https://opensource.google/docs/cla/#troubleshoot)).
> * The email used to register you as an authorized contributor must be the email used for the Git commit. Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * The email used to register you as an authorized contributor must also be [attached to your GitHub account](https://github.com/settings/emails).
> 
> ℹ️ **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter_markdown%2Fpull%2F301) for more info**.

@googlebot I signed it!

2020-11-17 03:56 UTC, domesticmouse commented
@cebr76 can you please investigate the CI failures?

2020-11-19 06:00 UTC, domesticmouse commented
@cebr76 and @MarkusWendorf I get the feeling this PR and #306 are in conflict. I'd prefer not to play the role of decider if the two of you can come to an agreement on API surface for this capability.

For what it's worth, both APIs lack testing of the newly introduced API surface, so that needs to be expanded as well. 

Thanks!

2020-11-19 06:02 UTC, domesticmouse requested changes
Needs testing, and de-contesting with #306

2021-01-25 22:39 UTC, quiverware commented
Hi @cebr76. I've been reviewing your PR and have questions about your proposed code changes. I see you are trying to get a padding value from a 'padding' attribute attached to a list element. Can you please elaborate on how this padding value is to be set? The flutter_markdown package uses the Dart markdown package to parse the source Markdown file into an abstract syntax tree (AST). The elements in the AST, and any attributes associated with an element, are generated by the markdown package or an instance of a custom BlockSyntax or InlineSyntax object. I'm not aware of any attributes assigned to the 'li' by the markdown package and checked to verify my assumption. I do not see the assignment of a 'padding' attribute in the markdown package code. The widget.dart file in the flutter_markdown package defines a TaskListSyntax class to allow for a custom implementation of an inline task list element but I do not see anything in your PR to parse and set a 'padding' attribute. I'm unable to see any way to set a padding value for a bullet list item. If your intent was to define a custom InlineSyntax class and corresponding MarkdownElementBuilder, you can make these customizations to the implementation of your Flutter app without any changes to the flutter_markdown package.

I agree with the intent of your PR, i.e. that it would be good as well as convenient for the flutter_markdown package to provide more layout controls, including padding for list items. I'm not sure I agree with the approach you are suggesting as it would require additional layout information to be included in the Markdown tag. This approach is not consistent with any of the Markdown specifications. I believe a better approach is to include padding information in the MarkdownStyleSheet since the style sheet is independent from the Markdown tag. See #306.

cc: @domesticmouse

2021-01-26 22:31 UTC, domesticmouse commented
Closing this out as I've landed #306

2021-01-26 22:31 UTC, closed without merging